apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-api.name" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "redis-api.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "redis-api.name" . }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis-api.name" . }}-secret
                  key: REDIS_PASSWORD
          command:
            - "redis-server"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "redis-api.name" . }}-pvc
