apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-api.name" . }}
  labels:
    {{- include "redis-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redis-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis-api.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REDIS_HOST
              value: "{{ include "redis-api.name" . }}-redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis-api.name" . }}-secret
                  key: REDIS_PASSWORD

